import type { DreamTeamContent } from "./dream-team-types";

export const ABOUT_DREAM_TEAM_CONTENT: DreamTeamContent = {
  label: "OUR TEAM",
  title: "The Dream",
  titleAccent: "Team",
  quote: "Alone we can do so little, together we can do so much.",
  members: [
    {
      id: "1",
      name: "Sahaya Sachin",
      role: "CEO",
      initials: "SS",
      image: "/images/teams/1-300x300.jpg",
      gradient: "pink-rose",
    },
    {
      id: "2",
      name: "Anand Grandhi",
      role: "CO-FOUNDER, AI AUTOMATION",
      initials: "AG",
      image: "/images/teams/2-300x300.jpg",
      gradient: "purple-indigo",
    },
    {
      id: "3",
      name: "Mohit Goyal",
      role: "ADVISOR, STRATEGY & OPERATIONS",
      initials: "MG",
      image: "/images/teams/3.png",
      gradient: "blue-cyan",
    },
    {
      id: "4",
      name: "Edwin Pranata",
      role: "ADVISOR, GLOBAL BUSINESS DEVELOPMENT",
      initials: "EP",
      image: "/images/teams/4.png",
      gradient: "violet-purple",
    },
    {
      id: "5",
      name: "Mohandhas V",
      role: "CREATIVE CONSULTANT",
      initials: "MV",
      image: "/images/teams/5.png",
      gradient: "orange-red",
    },
    {
      id: "6",
      name: "Manikandan K",
      role: "SR. SEO CONSULTANT",
      initials: "MK",
      image: "/images/teams/1521333501361.jpg",
      gradient: "green-emerald",
    },
    {
      id: "7",
      name: "Sahaya Tharini",
      role: "SR. CONTENT DEVELOPER",
      initials: "ST",
      image: "/images/teams/tharini.jpg",
      gradient: "pink-rose-soft",
    },
    {
      id: "8",
      name: "Ashish T Jacob",
      role: "SR. CONTENT CONSULTANT",
      initials: "AJ",
      image: "/images/teams/ashish-jacob.png",
      gradient: "cyan-blue",
    },
  ],
};
