import type { DreamTeamContent } from "./dream-team-types";

export const ABOUT_DREAM_TEAM_CONTENT: DreamTeamContent = {
  label: "OUR TEAM",
  title: "The Dream",
  titleAccent: "Team",
  quote: "Alone we can do so little, together we can do so much.",
  members: [
    {
      id: "1",
      name: "Sachin",
      role: "CEO",
      initials: "SC",
      image: "/images/teams/2-300x300.jpg",
      gradient: "pink-rose",
    },
    {
      id: "2",
      name: "Anand Grandhi",
      role: "AI AUTOMATION SPECIALIST",
      initials: "AG",
      image: "/images/teams/1-300x300.jpg",
      gradient: "purple-indigo",
    },
    {
      id: "3",
      name: "Akivito Achumi",
      role: "PERFORMANCE MARKETER",
      initials: "AA",
      image: "/images/teams/Akivito.png",
      gradient: "blue-cyan",
    },
    {
      id: "4",
      name: "Soumya Hosmani",
      role: "MARKETING COORDINATOR",
      initials: "SH",
      image: "/images/teams/Soumya Hosmani Marketing Coordinator.png",
      gradient: "violet-purple",
    },
    {
      id: "5",
      name: "Anam Afreen",
      role: "SEO CONSULTANT",
      initials: "AF",
      image: "/images/teams/Anam.jpeg",
      gradient: "orange-red",
    },
    {
      id: "6",
      name: "Manikandan",
      role: "SR. SEO CONSULTANT",
      initials: "MK",
      image: "/images/teams/1521333501361.jpg",
      gradient: "green-emerald",
    },
    {
      id: "7",
      name: "Sahaya",
      role: "SR. CONTENT DEVELOPER",
      initials: "SA",
      image: "/images/teams/tharini.jpg",
      gradient: "pink-rose-soft",
    },
    {
      id: "8",
      name: "Ashish",
      role: "SR. CONTENT CONSULTANT",
      initials: "AS",
      image: "/images/teams/ashish-jacob.png",
      gradient: "cyan-blue",
    },
    {
      id: "9",
      name: "Mohit",
      role: "ADVISOR, STRATEGY & OPERATIONS",
      initials: "MO",
      image: "/images/teams/3.png",
      gradient: "pink-rose",
    },
    {
      id: "10",
      name: "Edwin",
      role: "ADVISOR, GLOBAL BUSINESS DEVELOPMENT",
      initials: "ED",
      image: "/images/teams/4.png",
      gradient: "purple-indigo",
    },
  ],
};
